name: vectorlovers
favicon: null
layout_spectrum: 0.5730336927808821
typography_spectrum: 0.17728022672235966
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5353022480849177
  lightness: 0.4689994789659977
  saturation: 0.07917869719676673
  rhythmicContrast: 0.9477412460837513
purpose: []
